version: "3.8"

services: 
  citation-api:
    hostname: citation-api
    container_name: citation-api
    build: ./
    volumes: 
      - ./citation-api:/app:rw
    env_file:
      - .env
    ports:
      - ${APP_PORT}
    # stdin_open: true
    # command: sleep infinity