# Use an official Python runtime as a parent image
FROM python:3.12.0-slim

# Set the working directory to /app
WORKDIR /app

COPY ./requirements.txt ./.env /app
# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
# ENV APP_ENV=prod

# Run app.py when the container launches
CMD ["python", "/app/api.py"]